<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MPetugas extends CI_Model
{

    public $table = 'petugas';
    public $id = 'id_petugas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    

    function get_key($username) {
        $this->db->select('p. username , p. nama_lengkap, p. password, p. hak_akses, s.key');
        $this->db->from('petugas p');
        $this->db->where('p.username', $username);
        $this->db->join('keys s', 'p.id_petugas = s.user_id', 'left');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_petugas', $q);
    $this->db->or_like('nama_lengkap', $q);
    $this->db->or_like('email', $q);
    $this->db->or_like('nipos', $q);
    $this->db->or_like('no_telp', $q);
    $this->db->or_like('status_pegawai', $q);
    $this->db->or_like('alamat', $q);
    $this->db->or_like('username', $q);
    $this->db->or_like('password', $q);
    $this->db->or_like('hak_akses', $q);
    $this->db->or_like('id_kantor', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {

    //join tabel kantor
    $this->db->select('p.*,k.nama_kota');
    $this->db->from('petugas p');
    $this->db->join('kantor k', 'k.id_kantor = p.id_kantor');

        $this->db->order_by('p.id_petugas', $this->order);
        $this->db->like('p.id_petugas', $q);
    $this->db->or_like('p.nama_lengkap', $q);
    $this->db->or_like('p.email', $q);
    $this->db->or_like('p.nipos', $q);
    $this->db->or_like('p.no_telp', $q);
    $this->db->or_like('p.status_pegawai', $q);
    $this->db->or_like('p.alamat', $q);
    $this->db->or_like('p.username', $q);
    $this->db->or_like('p.password', $q);
    $this->db->or_like('p.hak_akses', $q);
    $this->db->or_like('p.id_kantor', $q);
    $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return $this->db->insert_id();
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MPetugas.php */
/* Location: ./application/models/MPetugas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-06-27 06:12:43 */
/* http://harviacode.com */